services:
  db:
    image: mysql:9.7.0
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DATABASE}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p${DB_PASS}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - databaseNetwork

  server:
    build: .
    # restart: always
    volumes:
      - ./:/belajar
      - /belajar/node_modules
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - databaseNetwork

networks:
  databaseNetwork: 
    external: true
